apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-flow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-flow
  template:
    metadata:
      labels:
        app: test-flow
    spec:
      containers:
        - name: test-flow
          image: prathamesh0505/test-flow:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test-flow-service
spec:
  type: LoadBalancer
  selector:
    app: test-flow
  ports:
    - port: 80
      targetPort: 80